// <auto-generated />
using System;
using FindMyRouteAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindMyRouteAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230215171717_test2")]
    partial class test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FindMyRouteAPI.Modul.Models.KreditnaKartica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BrojKartice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Korisnik_id")
                        .HasColumnType("int");

                    b.Property<string>("SigurnosniBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Korisnik_id");

                    b.ToTable("KreditnaKartica");
                });

            modelBuilder.Entity("FindMyRouteAPI.Modul.Models.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Osoba");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Osoba");
                });

            modelBuilder.Entity("FindMyRouteAPI.Modul.Models.Administrator", b =>
                {
                    b.HasBaseType("FindMyRouteAPI.Modul.Models.Osoba");

                    b.Property<string>("PIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("FindMyRouteAPI.Modul.Models.Korisnik", b =>
                {
                    b.HasBaseType("FindMyRouteAPI.Modul.Models.Osoba");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojKupljenihKarata")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Korisnik");
                });

            modelBuilder.Entity("FindMyRouteAPI.Modul.Models.RadnikFirme", b =>
                {
                    b.HasBaseType("FindMyRouteAPI.Modul.Models.Osoba");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadniStaz")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("RadnikFirme");
                });

            modelBuilder.Entity("FindMyRouteAPI.Modul.Models.KreditnaKartica", b =>
                {
                    b.HasOne("FindMyRouteAPI.Modul.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("Korisnik_id");

                    b.Navigation("Korisnik");
                });
#pragma warning restore 612, 618
        }
    }
}
